/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.automato.finito.screens;

import com.mycompany.automato.finito.classes.AutomatonManager;
import com.mycompany.automato.finito.classes.TransitionState;
import com.mycompany.automato.finito.constants.Automatons;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joao_
 */
public class MainScreen extends javax.swing.JFrame {

    ArrayList<AutomatonManager> automatons;
    int indexOfAutomatonSelected;

    public MainScreen() {
        this.automatons = new Automatons().initializeAutomatonConstants();
        initComponents();
        comboBoxChooseAutomaton.removeAllItems();
        automatons.forEach((AutomatonManager automaton) -> {
            comboBoxChooseAutomaton.addItem(String.valueOf(automaton.getExercise()));
        });
        
        this.indexOfAutomatonSelected = 0;
        textFieldDescription.setText(automatons.get(indexOfAutomatonSelected).getDescription());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelChooseAutomaton = new javax.swing.JLabel();
        comboBoxChooseAutomaton = new javax.swing.JComboBox<>();
        labelChooseAutomaton1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldSentence = new javax.swing.JTextField();
        buttonCleanSentence = new javax.swing.JButton();
        buttonExecuteSentence = new javax.swing.JButton();
        labelChooseAutomaton2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaSequence = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        textFieldSentenceAccepted = new javax.swing.JTextField();
        PannelColorSentence = new javax.swing.JPanel();
        textFieldDescription = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelChooseAutomaton.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        labelChooseAutomaton.setText("Escolha o Autômato Desejado");

        comboBoxChooseAutomaton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxChooseAutomaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxChooseAutomatonActionPerformed(evt);
            }
        });

        labelChooseAutomaton1.setText("Descrição do Autômato");

        jLabel1.setText("Sentença");

        textFieldSentence.setToolTipText("Escreva a Sentença Aqui");
        textFieldSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSentenceActionPerformed(evt);
            }
        });

        buttonCleanSentence.setText("Limpar Sentença");
        buttonCleanSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCleanSentenceActionPerformed(evt);
            }
        });

        buttonExecuteSentence.setText("Executar Sentença");
        buttonExecuteSentence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExecuteSentenceActionPerformed(evt);
            }
        });

        labelChooseAutomaton2.setText("Sequência de passos");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AUTÔMATO RECONHECEDOR DE SENTENÇAS");

        textAreaSequence.setColumns(20);
        textAreaSequence.setRows(5);
        jScrollPane2.setViewportView(textAreaSequence);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Saída:");

        textFieldSentenceAccepted.setEditable(false);
        textFieldSentenceAccepted.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        PannelColorSentence.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PannelColorSentenceLayout = new javax.swing.GroupLayout(PannelColorSentence);
        PannelColorSentence.setLayout(PannelColorSentenceLayout);
        PannelColorSentenceLayout.setHorizontalGroup(
            PannelColorSentenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PannelColorSentenceLayout.setVerticalGroup(
            PannelColorSentenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        textFieldDescription.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelColorSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelChooseAutomaton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelChooseAutomaton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboBoxChooseAutomaton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textFieldSentenceAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelChooseAutomaton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldSentence)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(buttonCleanSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buttonExecuteSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxChooseAutomaton)
                    .addComponent(labelChooseAutomaton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(labelChooseAutomaton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldSentence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCleanSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExecuteSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelChooseAutomaton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSentenceAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(PannelColorSentence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Opções");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Este reconhecedor de autômatos foi construído por Gustavo Mamoto Kazioka e João Luiz Gomes");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void buttonExecuteSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExecuteSentenceActionPerformed
        String sentence = textFieldSentence.getText();
        char[] arraySymbols = sentence.toCharArray();
        System.out.println(this.indexOfAutomatonSelected);
        ArrayList<Integer> stateSequence = this.automatons.get(this.indexOfAutomatonSelected).readSentence(arraySymbols);
        
                     
        if(this.automatons.get(this.indexOfAutomatonSelected).isFinalState(stateSequence.get(stateSequence.size()-1))){
            textFieldSentenceAccepted.setText("Sentença Reconhecida");
            PannelColorSentence.setBackground(Color.GREEN);
        }else{
            textFieldSentenceAccepted.setText("Sentença não Reconhecida");
            PannelColorSentence.setBackground(Color.RED);
        }
        
        this.getStateSequenceFormated(stateSequence);
    }//GEN-LAST:event_buttonExecuteSentenceActionPerformed

    private void getStateSequenceFormated(ArrayList<Integer> stateSequence){
        int currentIndex = 0;
        String sequenceString = "";

        for(currentIndex = 0; currentIndex < stateSequence.size() - 1; currentIndex++){
            if(stateSequence.get(currentIndex+1)==-1)
                sequenceString = sequenceString.concat("SÍMBOLO NÃO RECONHECIDO");
            else
                sequenceString = sequenceString.concat(String.format("q(%s) -> q(%s)\n", stateSequence.get(currentIndex), stateSequence.get(currentIndex+1)));
        }
        textAreaSequence.setText(sequenceString);
    }
    
    private void buttonCleanSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCleanSentenceActionPerformed
        textFieldSentence.setText("");
    }//GEN-LAST:event_buttonCleanSentenceActionPerformed

    private void textFieldSentenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSentenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSentenceActionPerformed

    private void comboBoxChooseAutomatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxChooseAutomatonActionPerformed
        if(comboBoxChooseAutomaton.getSelectedItem() != null){
            this.indexOfAutomatonSelected = comboBoxChooseAutomaton.getSelectedIndex();
            
            textFieldDescription.setText(automatons.get(this.indexOfAutomatonSelected).getDescription());
            
        }
        
    }//GEN-LAST:event_comboBoxChooseAutomatonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PannelColorSentence;
    private javax.swing.JButton buttonCleanSentence;
    private javax.swing.JButton buttonExecuteSentence;
    private javax.swing.JComboBox<String> comboBoxChooseAutomaton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelChooseAutomaton;
    private javax.swing.JLabel labelChooseAutomaton1;
    private javax.swing.JLabel labelChooseAutomaton2;
    private javax.swing.JTextArea textAreaSequence;
    private javax.swing.JTextField textFieldDescription;
    private javax.swing.JTextField textFieldSentence;
    private javax.swing.JTextField textFieldSentenceAccepted;
    // End of variables declaration//GEN-END:variables
}
